##################################################################################################################
#                          > Plugin by: Pozdro320 <
#                          > Wersja: 1.0 <
#
#  Wszelkie bledy nalezy zglaszac poprzez:
#  1. Wiadomosc prywatna na Discord (DM): Pozdro320
#
##################################################################################################################

database:
  # Typ zapisu: MYSQL, MARIADB lub YML
  type: "MYSQL"
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""
  table-prefix: "pozdro_"
  ssl: false
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 5000
    max-lifetime: 1800000

# | Sekcja komend wykonywanych podczac danej akcji:                             |
# | Dostepne zmienne: {PLAYER} - nick gracza, {MODERATOR} - nick sprawdzającego |
commands:
  cheats-detected:
    - "tempban {PLAYER} 7d &#FF0000Wykryto niedozwolone modyfikacje &8(&#00C0F1{MODERATOR}&8)"
  admission:
    - "tempban {PLAYER} 4d &#FF8600Przyznanie się do posiadania cheatów &8(&#00C0F1{MODERATOR}&8)"
  lack-of-cooperation:
    - "tempban {PLAYER} 14d &#FF0000Brak współpracy podczas kontroli &8(&#00C0F1{MODERATOR}&8)"
  logged-out:
    - "tempban {PLAYER} 14d &#FF0000Opuszczenie gry podczas sprawdzania &8(&#00C0F1{MODERATOR}&8)"


# | Sekcja zapisu logów w histori                                              |
history-reasons:
  clean: "UZNANO ZA CZYSTEGO"
  cheats: "ZBANOWANY (CHEATY)"
  admission: "ZBANOWANY (PRZYZNANIE SIE)"
  no-cooperation: "ZBANOWANY (BRAK WSPÓŁPRACY)"
  logout: "ZBANOWANY (WYLOGOWAŁ SIĘ)"


# | Sekcja lokalizacji:                                                        |
# | Ustawiane automatycznie przez komendy /sprawdzarka <set-checker|set-spawn> |
locations:
  checker: {}
  spawn: {}


# | Wyższa liczba = większa siła. Moderator musi mieć WIĘCEJ punktów niż sprawdzany.  |
# | Przykład: 'moderator'(50) sprawdzi 'helpera'(30), ale nie sprawdzi 'admina'(100). |
hierarchy:
  enabled: false
  rang:
    gracz: 0
    vip: 1
    helper: 10
    mod: 20
    admin: 100
    wlasciciel: 1000


# | Lista komend, których gracz MOŻE używać podczas sprawdzania. |
# | Wszystkie inne komendy zostaną automatycznie zablokowane.    |
allowed-commands:
  - "/msg"
  - "/tell"
  - "/w"
  - "/r"
  - "/helpop"
  - "/przyznajesie"