##################################################################################################################
#                          > Plugin by: Pozdro320 <
#                          > Wersja: 1.0 <
#
#  Wszelkie bledy nalezy zglaszac poprzez:
#  1. Wiadomosc prywatna na Discord (DM): Pozdro320
#
##################################################################################################################

# | Sekcja komend wykonywanych podczac danej akcji:                             |
# | Dostepne zmienne: {PLAYER} - nick gracza, {MODERATOR} - nick sprawdzającego |
commands:
  cheats-detected:
  - tempban {PLAYER} 7d &8» &fWykryto &5cheaty &fpodczas kontroli!
    &8(&b{MODERATOR}&8)

  admission:
  - tempban {PLAYER} 5d &8» &fGracz &b{PLAYER} &fprzyznal sie
    do cheatow.

  lack-of-cooperation:
  - tempban {PLAYER} 14d &8» &fBrak wspolpracy z administratorem
    &b{MODERATOR}&f.

  logged-out:
  - tempban {PLAYER} 14d &8» &fGracz &b{PLAYER} &fwylogowal sie
    podczas sprawdzania!


# | Sekcja zapisu logów w histori                                              |
history-reasons:
  clean: "UZNANO ZA CZYSTEGO"
  cheats: "ZBANOWANY (CHEATY)"
  admission: "ZBANOWANY (PRZYZNANIE SIE)"
  no-cooperation: "ZBANOWANY (BRAK WSPÓŁPRACY)"
  logout: "ZBANOWANY (WYLOGOWAŁ SIĘ)"


# | Sekcja lokalizacji:                                                        |
# | Ustawiane automatycznie przez komendy /sprawdzarka <set-checker|set-spawn> |
locations:
  checker: {}
  spawn: {}


# | Wyższa liczba = większa siła. Moderator musi mieć WIĘCEJ punktów niż sprawdzany.  |
# | Przykład: 'moderator'(50) sprawdzi 'helpera'(30), ale nie sprawdzi 'admina'(100). |
hierarchy:
  enabled: false
  rang:
    gracz: 0
    vip: 1
    helper: 10
    mod: 20
    admin: 100
    wlasciciel: 1000


# | Lista komend, których gracz MOŻE używać podczas sprawdzania. |
# | Wszystkie inne komendy zostaną automatycznie zablokowane.    |
allowed-commands:
  - "/msg"
  - "/tell"
  - "/w"
  - "/r"
  - "/helpop"
  - "/przyznajesie"